#!/usr/bin/env python
# This file goes through the data directory, looking for source files that
# match the input pattern, parses these files and extracts out key words from
# the files.
# Usage:
# ./extract_key_words -s <comma separated suffix list> -o <outfile>

import key_word_extractor as ke
import os

# root data directory
root_dir=os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
root_data_dir=os.path.join(root_dir, 'data')
key_word_dir=os.path.join(root_dir, 'key_words')
if not os.path.exists(key_word_dir):
  os.makedirs(key_word_dir)
# number of keywords to extract
max_key_words=1000
percentile_key_words=95

# list of languages, corresponding file suffixes, a flag indicating whether
# to parse or skip, a list of data directories to read
suffixes  = 'suffixes'
parse     = 'parse'
data_dirs = 'data_dirs'
outfile   = 'outfile'
languages = {
    'h'      : { suffixes  : ['h'],
                 parse     : False,
                 data_dirs : [ root_data_dir ],
                 outfile   : os.path.join(key_word_dir, "h")
               },
    'c'      : { suffixes  : ['h', 'c', 'cc', 'cpp'],
                 parse     : True,
                 data_dirs : [ root_data_dir ],
                 outfile   : os.path.join(key_word_dir, "c")
               },
    'python' : { suffixes  : ['py'],
                 parse     : False,
                 data_dirs : [ root_data_dir ],
                 outfile   : os.path.join(key_word_dir, "python")
               }
    }

# Extract key words and save them
for lang, val in languages.items():
  val = languages[lang]
  if not val[parse]:
    print("Skipping language %s" % lang)
    continue
  print("Extracting key words for language %s ..." % lang)
  words = ke.FrequentWords(data_dirs=val[data_dirs], suffixes=val[suffixes],
                           max_key_words=max_key_words,
                           percentile_key_words=percentile_key_words)
  with open(val[outfile], 'w') as out:
    for key_word, count in words:
      out.write("%s %d\n" % (key_word, count))
  print("Completed extracting key words for language %s" % lang)
